---
apiVersion: v2
type: application
name: unifi
description: The unifi software is a powerful, enterprise wireless software engine ideal for high-density client deployments requiring low latency and high uptime performance.
version: 1.0.0
appVersion: 10.1.85-ls119
maintainers:
  - name: qaoru
    email: paul@qaoru.fr
keywords:
  - network
  - unifi
dependencies:
  - condition: metrics.enabled
    name: unpoller
    repository: https://unpoller.github.io/helm-chart
    version: 2.2.0
