{{- if .Values.database.credentials.generate }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.database.credentials.secretName }}"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.database.credentials.secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $passwordSecret := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
  username: {{ "unifi" | b64enc | quote }}
  password: {{ $passwordSecret | quote }}
{{- end }}

---
{{- if and .Values.metrics.enabled .Values.metrics.unifiCredentials.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.metrics.unifiCredentials.secretName }}"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.metrics.unifiCredentials.secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $passwordSecret := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
  username: {{ "kube-metrics" | b64enc | quote }}
  password: {{ $passwordSecret | quote }}
{{- end }}