image:
  repository: linuxserver/unifi-network-application
  tag: ~
  pullPolicy: IfNotPresent

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Paris"
  # Add custom env here if needed
  # EXTRA_ARGS: ""
extraEnv: []  # list of { name: "", value: "" }

database:
  host: "mongodb"
  port: 27017
  dbName: unifi
  authSource: admin
  credentials:
    generate: false
    secretName: "unifi-db-credentials"
    usernameKey: "username"
    passwordKey: "password"
  initCredentials:
    secretName: "unifi-db-credentials"
    usernameKey: "admin-username"
    passwordKey: "admin-password"

networkPolicy:
  enabled: false
  cilium:
    egress:
    - toFQDNs:
      - matchName: fw-update.ubnt.com
      - matchName: fw-download.ubnt.com
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s:k8s-app: kube-dns
      toPorts:
      - ports:
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP
        rules:
          dns:
          - matchName: fw-update.ubnt.com
          - matchName: fw-download.ubnt.com
    ingress:
    - toPorts:
      - ports:
        - port: http-inform
  flavor: kubernetes
  ingress:
  - ports:
    - protocol: TCP
      port: http-inform
  egress: {}

# Pod settings
replicaCount: 1
revisionHistoryLimit: 3

podAnnotations: {}
podLabels: {}
podPorts:
  https-ui:
    containerPort: 8443
    protocol: TCP
  http-inform:
    containerPort: 8080
    protocol: TCP
  guest-https:
    containerPort: 8843
    protocol: TCP
  guest-http:
    containerPort: 8880
    protocol: TCP
  speedtest:
    containerPort: 6789
    protocol: TCP
  stun:
    containerPort: 3478
    protocol: UDP
  discovery:
    containerPort: 10001
    protocol: UDP
  syslog:
    containerPort: 5514
    protocol: UDP

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    memory: 2Gi

initContainerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ['ALL']

containerSecurityContext: ~

podSecurityContext:
  runAsUser: 0
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"

# Probes against the controller UI on 8443
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 6
  readiness:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 12

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Persistent data at /config
persistence:
  enabled: true
  storageClass: ""
  accessModes: ["ReadWriteOnce"]
  size: 5Gi
  annotations: {}

services:
  # internal use only because other port must be reachable from devices
  internal:
    enabled: true
    type: ClusterIP
    annotations: {}
    loadBalancerIP: ""
    # must refer to podPorts
    enablePorts:
      https-ui: true
      http-inform: false
      guest-https: false
      guest-http: false
      speedtest: false
      stun: false
      discovery: false
      syslog: false
  public:
    enabled: false
    type: LoadBalancer
    annotations: {}
    loadBalancerIP: ""
    enablePorts:
      https-ui: false
      http-inform: true
      guest-https: true
      guest-http: true
      speedtest: true
      stun: true
      discovery: true
      syslog: true

ingress:
  enabled: false
  className: ""
  annotations:
    server-ssl: "true"
  hosts:
    - host: unifi.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: [] # e.g. [{ hosts: ["unifi.example.com"], secretName: unifi-tls }]

nodeSelector: {}
tolerations: []
affinity: {}

# Extra containers/volumes if you need sidecars or custom mounts
extraVolumeMounts: []
extraVolumes: []


metrics:
  enabled: false

  # generate monitoring credentials, you must configure it after pod bootstrap
  unifiCredentials:
    generate: true
    secretName: "unifi-metrics-credentials"
    usernameKey: "username"
    passwordKey: "password"

unpoller:
  extraEnv:
  - name: UP_UNIFI_CONTROLLER_0_URL
    value: "https://unifiunpoller:8443"
  - name: UP_UNIFI_CONTROLLER_0_USER
    valueFrom:
      secretKeyRef:
        name: unifi-metrics-credentials
        key: username
  - name: UP_UNIFI_CONTROLLER_0_PASS
    valueFrom:
      secretKeyRef:
        name: unifi-metrics-credentials
        key: password


metrics:
  enabled: false

  # generate monitoring credentials, you must configure it after pod bootstrap
  unifiCredentials:
    generate: true
    secretName: "unifi-metrics-credentials"
    usernameKey: "username"
    passwordKey: "password"

unpoller:
  extraEnv:
  - name: UP_UNIFI_CONTROLLER_0_URL
    value: "https://unifiunpoller:8443"
  - name: UP_UNIFI_CONTROLLER_0_USER
    valueFrom:
      secretKeyRef:
        name: unifi-metrics-credentials
        key: username
  - name: UP_UNIFI_CONTROLLER_0_PASS
    valueFrom:
      secretKeyRef:
        name: unifi-metrics-credentials
        key: password